plugins: 
  eslint:
    enabled: true
    channel: "eslint-7"
    checks:
      complexity:
        enabled: true
      max-params:
        enabled: true
      prettier/prettier:
        enabled: false