plugins: 
  eslint:
    enabled: true
    channel: "eslint-7"
    checks:
      complexity:
        enabled: true
      max-params:
        enabled: true


exclude_patterns:
- "tests/"
- "spec/"
- "src/deprecated-syntax-selectors.js"
- "src/package.js"
- "config/"
- "db/"
- "dist/"
- "features/"
- "**/node_modules/"
- "script/"
- "**/spec/"
- "**/test/"
- "**/tests/"
- "Tests/"
- "**/vendor/"
- "**/*_test.go"
- "**/*.d.ts"